name: gamerec
channels:
 - conda-forge
 - defaults
dependencies:
 - python=3.8.11
 - pip
 - pip:
   - openai
   - alive-progress
   - audio-recorder-streamlit
   - faiss-cpu
   - google-api-python-client
   - jq
   - langchain
   - openai
   - streamlit
   - tiktoken
   - youtube-transcript-api
