name: gamerec
channels:
 - conda-forge
 - defaults
dependencies:
 - python=3.8.11
 - pip
 - pip:
   - alive-progress
   # - faiss-cpu
   - google-api-python-client
   - jq
   # - langchain
   - openai
   - pinecone-client
   - semantic-kernel
   - streamlit
   - tiktoken
   - youtube-transcript-api
